apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-configmap.yaml
  - api.yaml
  - api-hpa.yaml
  - migrate-job.yaml
  - admin.yaml
  - portal.yaml
  - platform-admin.yaml
  - network-policy.yaml
  - ingress-platform.yaml
  - ingress-custom-domains.yaml
  - tls-secret-placeholder.yaml
  - ingress-controller-notes.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: full-sales
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
