//! Demo product and category asset specs (FoodKing PNGs under `assets/`).

use uuid::Uuid;

use crate::ids::product_ids;

pub struct DemoProduct {
    pub id: Uuid,
    pub sku: &'static str,
    pub name: &'static str,
    pub price: i64,
    pub category_idx: usize,
    pub active: bool,
    pub description: &'static str,
    pub unit: &'static str,
    pub asset: &'static str,
    pub object_key: &'static str,
}

pub fn demo_products() -> Vec<DemoProduct> {
    let ids = product_ids();
    vec![
        DemoProduct {
            id: ids[0],
            sku: "SEED-001",
            name: "Coca-Cola 2L",
            price: 8_99,
            category_idx: 0,
            active: true,
            description: "Refrigerante cola 2 litros — gelado e refrescante.",
            unit: "Unit",
            asset: "products/coca-cola-2l.png",
            object_key: "products/coca-cola-2l.png",
        },
        DemoProduct {
            id: ids[1],
            sku: "SEED-002",
            name: "Guaraná Antarctica 2L",
            price: 7_49,
            category_idx: 0,
            active: true,
            description: "Refrigerante guaraná 2 litros.",
            unit: "Unit",
            asset: "products/guarana-2l.png",
            object_key: "products/guarana-2l.png",
        },
        DemoProduct {
            id: ids[2],
            sku: "SEED-003",
            name: "Água Crystal 500ml",
            price: 2_50,
            category_idx: 0,
            active: true,
            description: "Água mineral sem gás 500 ml.",
            unit: "Unit",
            asset: "products/agua-mineral-500ml.png",
            object_key: "products/agua-mineral-500ml.png",
        },
        DemoProduct {
            id: ids[3],
            sku: "SEED-004",
            name: "Suco Del Valle Laranja 1L",
            price: 9_90,
            category_idx: 0,
            active: true,
            description: "Suco de laranja integral 1 litro.",
            unit: "Unit",
            asset: "products/suco-laranja-1l.png",
            object_key: "products/suco-laranja-1l.png",
        },
        DemoProduct {
            id: ids[4],
            sku: "SEED-005",
            name: "Batata Chips Ruffles Original 165g",
            price: 12_90,
            category_idx: 1,
            active: true,
            description: "Batata chips ondulada sabor original.",
            unit: "Unit",
            asset: "products/batata-chips.png",
            object_key: "products/batata-chips.png",
        },
        DemoProduct {
            id: ids[5],
            sku: "SEED-006",
            name: "Amendoim Dori Torresmo 500g",
            price: 10_50,
            category_idx: 1,
            active: true,
            description: "Amendoim crocante sabor torresmo.",
            unit: "Unit",
            asset: "products/amendoim.png",
            object_key: "products/amendoim.png",
        },
        DemoProduct {
            id: ids[6],
            sku: "SEED-007",
            name: "Chocolate Bis ao Leite 126g",
            price: 6_99,
            category_idx: 1,
            active: true,
            description: "Wafer recheado coberto com chocolate ao leite.",
            unit: "Unit",
            asset: "products/chocolate.png",
            object_key: "products/chocolate.png",
        },
        DemoProduct {
            id: ids[7],
            sku: "SEED-008",
            name: "Detergente Ypê Neutro 500ml",
            price: 4_49,
            category_idx: 2,
            active: true,
            description: "Detergente líquido neutro para louças.",
            unit: "Unit",
            asset: "products/detergente.png",
            object_key: "products/detergente.png",
        },
        DemoProduct {
            id: ids[8],
            sku: "SEED-009",
            name: "Desinfetante Pinho Sol 1L",
            price: 11_90,
            category_idx: 2,
            active: true,
            description: "Desinfetante multiuso aroma pinho.",
            unit: "Unit",
            asset: "products/desinfetante.png",
            object_key: "products/desinfetante.png",
        },
        DemoProduct {
            id: ids[9],
            sku: "SEED-010",
            name: "Pizza Congelada Sadia Mussarela",
            price: 29_90,
            category_idx: 3,
            active: false,
            description: "Pizza congelada tradicional mussarela 460g.",
            unit: "Unit",
            asset: "products/pizza-congelada.png",
            object_key: "products/pizza-congelada.png",
        },
        DemoProduct {
            id: ids[10],
            sku: "SEED-011",
            name: "Arroz Tio João Tipo 1 1kg",
            price: 6_49,
            category_idx: 4,
            active: true,
            description: "Arroz branco tipo 1 pacote 1 kg.",
            unit: "Unit",
            asset: "products/arroz-1kg.png",
            object_key: "products/arroz-1kg.png",
        },
        DemoProduct {
            id: ids[11],
            sku: "SEED-012",
            name: "Feijão Carioca Camil 1kg",
            price: 7_99,
            category_idx: 4,
            active: true,
            description: "Feijão carioca selecionado 1 kg.",
            unit: "Unit",
            asset: "products/feijao-1kg.png",
            object_key: "products/feijao-1kg.png",
        },
    ]
}

pub const CATEGORY_ASSETS: [(&str, &str); 5] = [
    ("categories/bebidas.png", "categories/bebidas.png"),
    ("categories/snacks.png", "categories/snacks.png"),
    ("categories/limpeza.png", "categories/limpeza.png"),
    ("categories/congelados.png", "categories/congelados.png"),
    ("categories/mercearia.png", "categories/mercearia.png"),
];
