-- Application role for RLS-enforced connections (integration tests + API runtime).

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_user') THEN
        CREATE ROLE app_user LOGIN PASSWORD 'app_password' NOSUPERUSER NOBYPASSRLS;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA shared, identity, commerces, inventory, sales, reports TO app_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA identity TO app_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA commerces TO app_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA inventory TO app_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA sales TO app_user;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA reports TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA commerces GRANT SELECT, INSERT, UPDATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT SELECT, INSERT, UPDATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT SELECT, INSERT, UPDATE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reports GRANT SELECT, INSERT ON TABLES TO app_user;
