"""Render Phase 17 inventory and gap-baseline markdown."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .classify import ClassName, _needles, classify_all, load_test_files

Row = tuple[str, str, str, str, str, str, str, str]


def render_inventory(rows: list[Row]) -> str:
    counts: Counter[str] = Counter(r[3] for r in rows)
    lines = [
        "# Phase 17 — Route inventory (from docs/API-CONTRACT.md)",
        "",
        f"> Frozen snapshot: **{len(rows)}** endpoints. "
        "Regenerate: `pnpm verify:api-route-inventory -- --write-docs`.",
        "",
        "Coverage columns: **Happy** | **Authz** | **Errors** | **Journey** "
        "(see README). Journey `[x]` = E2E membership or Standalone "
        "(OD-17-1 B when Happy/Authz/Errors complete).",
        "",
        "| Domain | Count |",
        "|--------|------:|",
    ]
    for domain, n in sorted(counts.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"| {domain} | {n} |")
    lines += [
        "",
        "| ID | Method | Path | Domain | Happy | Authz | Errors | Journey |",
        "|----|--------|------|--------|:-----:|:-----:|:------:|:-------:|",
    ]
    for tid, method, path, domain, happy, authz, errors, journey in rows:
        lines.append(
            f"| {tid} | `{method}` | `{path}` | {domain} | "
            f"{happy} | {authz} | {errors} | {journey} |"
        )
    lines += [
        "",
        "## Drift checks",
        "",
        "1. Every row must exist in `backend/crates/api-http/src/routes.rs`.",
        "2. Every `.route(...)` in `routes.rs` must map to a contract section "
        "(or dated waiver in `scripts/api-route-inventory-allowlist.json`).",
        "3. CI: `pnpm verify:api-route-inventory` fails on mismatch.",
        "4. CI: `pnpm verify:route-contract-manifest` — every T-17-* has a test marker.",
        "",
    ]
    return "\n".join(lines)


def _example_files(path: str, files: dict[Path, str]) -> str:
    matched = sorted(
        {
            fpath.name
            for fpath, text in files.items()
            if any(n and n in text for n in _needles(path))
        }
    )[:4]
    return ", ".join(f"`{n}`" for n in matched) if matched else "—"


def render_gap_baseline(
    endpoints: list[tuple[str, str]],
    classes: dict[tuple[str, str], ClassName],
    id_by_ep: dict[tuple[str, str], str],
    tests_dir: Path,
) -> str:
    files = load_test_files(tests_dir)
    summary = Counter(classes.values())
    lines = [
        "# Phase 17 — Gap baseline (starting point)",
        "",
        "> Generated by `pnpm verify:api-route-inventory -- --write-docs`.",
        "> Do not mark inventory `[x]` until a real test asserts the contract.",
        "",
        "## Existing assets (reuse — do not rewrite blindly)",
        "",
        "| Location | Likely covers |",
        "|----------|----------------|",
        "| `tests/route_smoke.rs` | Mount smoke + sample 401 |",
        "| `tests/auth.rs` / `auth_matrix.rs` | Auth + role matrix |",
        "| `tests/sales*.rs` / `orders_admin.rs` / `deliveries.rs` | Sales / orders |",
        "| `tests/portal*.rs` / `public_catalog.rs` | Portal / public |",
        "| `tests/platform_*.rs` / `platform_saas*` | Platform SaaS |",
        "| `tests/billing_*.rs` | Billing / webhooks |",
        "| `tests/e2e*.rs` | Critical journeys |",
        "| `e2e/*.spec.ts` | Playwright (complement) |",
        "",
        "## Classification counts",
        "",
        "| Class | Count |",
        "|-------|------:|",
        f"| full | {summary.get('full', 0)} |",
        f"| partial | {summary.get('partial', 0)} |",
        f"| smoke-only | {summary.get('smoke-only', 0)} |",
        f"| none | {summary.get('none', 0)} |",
        f"| **Total** | **{len(endpoints)}** |",
        "",
        "## Per-route map",
        "",
        "| ID | Method | Path | Class | Example test files |",
        "|----|--------|------|-------|--------------------|",
    ]
    for method, path in sorted(endpoints, key=lambda ep: id_by_ep.get(ep, "Z")):
        tid = id_by_ep.get((method, path), "?")
        klass = classes[(method, path)]
        lines.append(
            f"| {tid} | `{method}` | `{path}` | {klass} | {_example_files(path, files)} |"
        )
    lines += [
        "",
        "## Notes",
        "",
        "- `none` / `smoke-only` / `partial` → finish in 17B–17J",
        "- `full` requires `// T-17-NNN` marker + Happy/Authz/Errors asserts",
        "- Cancel subscription implemented (17J); allowlist empty",
        "",
    ]
    return "\n".join(lines)


def write_docs(
    inventory_path: Path,
    gap_path: Path,
    rows: list[Row],
    endpoints: list[tuple[str, str]],
    tests_dir: Path,
) -> None:
    classes = classify_all(endpoints, tests_dir)
    id_by_ep = {(r[1], r[2]): r[0] for r in rows}
    inventory_path.parent.mkdir(parents=True, exist_ok=True)
    inventory_path.write_text(render_inventory(rows), encoding="utf-8")
    gap_path.write_text(
        render_gap_baseline(endpoints, classes, id_by_ep, tests_dir),
        encoding="utf-8",
    )
